# Run all three test executables and print summary.
# Invoke with: cmake -DTEST1_EXE=... -DTEST2_EXE=... -DTEST3_EXE=... -P run_tests.cmake
set(PASSED 0)
set(FAILED 0)

message(STATUS "")
message(STATUS "=== test_stoer_wagner ===")
execute_process(COMMAND "${TEST1_EXE}" RESULT_VARIABLE R1)
if(R1 EQUAL 0)
  message(STATUS "test_stoer_wagner: PASS")
  math(EXPR PASSED "${PASSED} + 1")
else()
  message(STATUS "test_stoer_wagner: FAIL (exit code ${R1})")
  math(EXPR FAILED "${FAILED} + 1")
endif()

message(STATUS "")
message(STATUS "=== test_planar_faces ===")
execute_process(COMMAND "${TEST2_EXE}" RESULT_VARIABLE R2)
if(R2 EQUAL 0)
  message(STATUS "test_planar_faces: PASS")
  math(EXPR PASSED "${PASSED} + 1")
else()
  message(STATUS "test_planar_faces: FAIL (exit code ${R2})")
  math(EXPR FAILED "${FAILED} + 1")
endif()

message(STATUS "")
message(STATUS "=== test_max_weighted_match ===")
execute_process(COMMAND "${TEST3_EXE}" RESULT_VARIABLE R3)
if(R3 EQUAL 0)
  message(STATUS "test_max_weighted_match: PASS")
  math(EXPR PASSED "${PASSED} + 1")
else()
  message(STATUS "test_max_weighted_match: FAIL (exit code ${R3})")
  math(EXPR FAILED "${FAILED} + 1")
endif()

message(STATUS "")
message(STATUS "Test suites passed: ${PASSED}, failed: ${FAILED}")
if(FAILED GREATER 0)
  message(STATUS "Overall: FAIL")
  message(FATAL_ERROR "Some tests failed.")
else()
  message(STATUS "Overall: PASS")
endif()
